### ISSUE TITLE
Bug: "Failed to change directory to /workspace" error after job completion

### ISSUE THREAD

**Issue by d-walsh** [All-Hands-AI/openhands-resolver#145]
```
Input tokens: 11820 | Output tokens: 80
23:00:58 - ACTION
AgentFinishAction(outputs={}, thought='It appears that there is no `test` directory in the project, which is why the test command is failing. Since the README updates did not require any changes to the application code, there are no tests to run.\n\nThe README file has been successfully updated to better represent the actual code and setup process. Since there are no tests to run, I will conclude the task.', action='finish')
23:00:58 - OBSERVATION
AgentStateChangedObservation(content='', agent_state=<AgentState.FINISHED: 'finished'>, observation='agent_state_changed')
23:00:58 - OBSERVATION
NullObservation(content='', observation='null')
23:00:58 - openhands:INFO: resolve_issues.py:131 - ------------------------------
23:00:58 - openhands:INFO: resolve_issues.py:132 - BEGIN Runtime Completion Fn
23:00:58 - openhands:INFO: resolve_issues.py:133 - ------------------------------
23:00:58 - ACTION
**CmdRunAction (source=None)**
COMMAND:
cd /workspace
23:00:58 - openhands:INFO: runtime.py:316 - 
-----------------------------------Container logs:-----------------------------------
    |23:00:58 - openhands:ERROR: client.py:379 - Error getting exit code from bash script
    |INFO:     172.17.0.1:46622 - "POST /execute_action HTTP/1.1" 200 OK
--------------------------------------------------------------------------------
23:00:58 - OBSERVATION
**CmdOutputObservation (source=None, exit code=2)**
cd /workspace
[Python Interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.11/bin/python]
openhands@ef80aeb72581:/workspace $ 
23:00:58 - OBSERVATION
AgentStateChangedObservation(content='', agent_state=<AgentState.STOPPED: 'stopped'>, observation='agent_state_changed')
23:00:58 - openhands:INFO: agent_controller.py:157 - AgentController task was cancelled
ERROR:root:  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 726, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 706, in main
    asyncio.run(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 562, in resolve_issues
    await asyncio.gather(*[run_with_semaphore(task) for task in tasks])
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 560, in run_with_semaphore
    return await task
           ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 403, in update_progress
    resolved_output = await output
                      ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 314, in process_issue
    return_val = await complete_runtime(runtime, base_commit)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 141, in complete_runtime
    raise RuntimeError(
ERROR:root:<class 'RuntimeError'>: Failed to change directory to /workspace. Observation: **CmdOutputObservation (source=None, exit code=2)**
cd /workspace
[Python Interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.11/bin/python]
openhands@ef80aeb72581:/workspace $ 
  0%|          | 0/1 [03:33<?, ?it/s]
Error: Process completed with exit code 1.
```

---
*This issue has been moved to All-Hands-AI/openhands#5051*

**Comment by neubig** [comment]
Hmm, this is strange. I'll definitely try to fix this, but in order to do so I'll have to figure out a way to reproduce.

**Comment by codegefluester** [comment]
I am seeing similar behavior where running into rate limits with Claude essentially makes the agent fail, even though it already started with git operations + wrote a changelog file. Running this in GitHub actions.

```
--------
10:53:54 - OBSERVATION
AgentStateChangedObservation(content='', agent_state=<AgentState.STOPPED: 'stopped'>, observation='agent_state_changed')
ERROR:root:  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 720, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 700, in main
    asyncio.run(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 556, in resolve_issues
    await asyncio.gather(*[run_with_semaphore(task) for task in tasks])
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 554, in run_with_semaphore
    return await task
           ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 397, in update_progress
    resolved_output = await output
                      ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 319, in process_issue
    success, success_explanation = guess_success(issue, state.history, llm_config)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openhands_resolver/resolve_issues.py", line 231, in guess_success
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/utils.py", line 1069, in wrapper
    raise e
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/utils.py", line 957, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/main.py", line 2955, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 505, in exception_type
    raise RateLimitError(

ERROR:root:<class 'litellm.exceptions.RateLimitError'>: litellm.RateLimitError: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your daily rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
```

**Comment by regismesquita** [comment]
Hi, I believe I am facing a similar issue, I just started using this tool so I am not certain, but seems that my resolver is failing after the work is done and when it is trying to exit the shell.

This error is happening both locally and on the github action.
```
2024-11-01 16:27:12,290 - DEBUG - [Agent Controller default] **CmdRunAction (source=None)**
THOUGHT: I've added a new section to the README.md file that explains:
1. How to use the OpenHands resolver by adding the 'fix-me' label
2. What the workflow does (attempts resolution, creates PR/branch, comments on issue, removes label)
3. Where to monitor the progress

Since this is just a documentation change to the README file, no tests need to be written or run.

Let me finish the task:
COMMAND:
exit
2024-11-01 16:27:12,290 - DEBUG - Adding CmdRunAction id=9 from AGENT
2024-11-01 16:27:12,291 - DEBUG - [runtime 8] Getting container logs...
2024-11-01 16:27:12,392 - ERROR - [runtime 8] Error during action execution: 500 Server Error: Internal Server Error for url: http://localhost:38352/execute_action
2024-11-01 16:27:12,393 - DEBUG - [runtime 8] Getting container logs...
2024-11-01 16:27:12,393 - DEBUG - [runtime 8]
-----------------------------------Container logs:-----------------------------------
    |16:27:12 - openhands:DEBUG: action_execution_server.py:164 - Running action:
    |**CmdRunAction (source=EventSource.AGENT)**
    |THOUGHT: I've added a new section to the README.md file that explains:
    |1. How to use the OpenHands resolver by adding the 'fix-me' label
    |2. What the workflow does (attempts resolution, creates PR/branch, comments on issue, removes label)
    |3. Where to monitor the progress
    |
    |Since this is just a documentation change to the README file, no tests need to be written or run.
    |
    |Let me finish the task:
    |COMMAND:
    |exit
    |16:27:12 - openhands:DEBUG: bash.py:51 - BASH PARSING command: exit
    |16:27:12 - openhands:DEBUG: bash.py:58 - BASH PARSING remaining:
    |16:27:12 - openhands:DEBUG: bash.py:170 - Executing command: exit
    |16:27:12 - openhands:DEBUG: bash.py:253 - Continuing bash with timeout=300
    |16:27:12 - openhands:ERROR: bash.py:131 - Bash shell EOF! self.shell.after=<class 'pexpect.exceptions.EOF'>, self.shell.before='exit\r\n'
    |16:27:12 - openhands:ERROR: action_execution_server.py:405 - Error processing command: Bash shell EOF
    |Traceback (most recent call last):
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 255, in _continue_bash
    |    self.shell.expect(self.__bash_expect_regex, timeout=timeout)
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 354, in expect
    |    return self.expect_list(compiled_pattern_list,
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 383, in expect_list
    |    return exp.expect_loop(timeout)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/expect.py", line 179, in expect_loop
    |    return self.eof(e)
    |           ^^^^^^^^^^^
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/expect.py", line 122, in eof
    |    raise exc
    |pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
    |<pexpect.pty_spawn.spawn object at 0xfe46e07e3170>
    |command: /usr/bin/su
    |args: [b'/usr/bin/su', b'openhands']
    |buffer (last 100 chars): ''
    |before (last 100 chars): 'exit\r\n'
    |after: <class 'pexpect.exceptions.EOF'>
    |match: None
    |match_index: None
    |exitstatus: None
    |flag_eof: True
    |pid: 37
    |child_fd: 10
    |closed: False
    |timeout: 30
    |delimiter: <class 'pexpect.exceptions.EOF'>
    |logfile: None
    |logfile_read: None
    |logfile_send: None
    |maxread: 2000
    |ignorecase: False
    |searchwindowsize: None
    |delaybeforesend: 0.05
    |delayafterclose: 0.1
    |delayafterterminate: 0.1
    |searcher: searcher_re:
    |    0: re.compile('\\[PEXPECT_BEGIN\\]\\s*(.*?)\\s*([a-z0-9_-]*)@([a-zA-Z0-9.-]*):(.+)\\s*\\[PEXPECT_END\\]')
    |
    |During handling of the above exception, another exception occurred:
    |
    |Traceback (most recent call last):
    |  File "/openhands/code/openhands/runtime/action_execution_server.py", line 402, in execute_action
    |    observation = await client.run_action(action)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/action_execution_server.py", line 165, in run_action
    |    observation = await getattr(self, action_type)(action)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/action_execution_server.py", line 172, in run
    |    return self.bash_session.run(action)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 298, in run
    |    output, exit_code = self._execute_bash(
    |                        ^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 172, in _execute_bash
    |    return self._continue_bash(
    |           ^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 273, in _continue_bash
    |    bash_prompt = self._get_bash_prompt_and_update_pwd()
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 132, in _get_bash_prompt_and_update_pwd
    |    raise RuntimeError('Bash shell EOF')
    |RuntimeError: Bash shell EOF
    |Stack (most recent call last):
    |  File "<frozen runpy>", line 198, in _run_module_as_main
    
    
    ...
    
    
        |16:27:15 - openhands:ERROR: action_execution_server.py:361 - HTTP exception occurred: Bash shell EOF
--------------------------------------------------------------------------------
2024-11-01 16:27:15,163 - INFO - **FatalErrorObservation**
Action execution failed: 500 Server Error: Internal Server Error for url: http://localhost:38352/execute_action
2024-11-01 16:27:15,163 - INFO - Finished.
2024-11-01 16:27:15,163 - DEBUG - Adding AgentStateChangedObservation id=12 from AGENT
2024-11-01 16:27:15,163 - DEBUG - Adding AgentStateChangedObservation id=13 from AGENT
```

**Comment by neubig** [comment]
I renamed this thread to be more detailed and be less "catch-all".
- @d-walsh: I also experienced the "failed to change to /workspace" error once myself but I'm still not sure why. I'll continue investigating.
- @codegefluester: I think that this is mostly covered by #239 , it should give you a better error when you get LLM-related errors. I'll track this there.
- @regismesquita I believe the error was discussed/fixed in #229, but please tell me otherwise.

**Comment by regismesquita** [comment]
@neubig it was. working as expected now.

**Comment by regismesquita** [comment]
Thanks for looking into it and fixing the issue.
