### ISSUE TITLE
Github workflow for this repo is failing on "unexpected keyword argument stop_sequences"

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/openhands-resolver#184]
Currently workflows for this repo are failing on

```bash
13:12:27 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #1 | You can customize retry values in the configuration.
13:12:42 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #2 | You can customize retry values in the configuration.
13:12:57 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #3 | You can customize retry values in the configuration.
13:13:12 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #4 | You can customize retry values in the configuration.
13:13:28 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #5 | You can customize retry values in the configuration.
13:14:00 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #6 | You can customize retry values in the configuration.
13:15:04 - openhands:ERROR: retry_mixin.py:47 - litellm.APIError: APIError: OpenAIException - Completions.create() got an unexpected keyword argument 'stop_sequences'. Attempt #7 | You can customize retry values in the configuration.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 854, in completion
    raise e
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 790, in completion
    self.make_sync_openai_chat_completion_request(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 649, in make_sync_openai_chat_completion_request
    raise e
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 631, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Completions.create() got an unexpected keyword argument 'stop_sequences'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/main.py", line 1597, in completion
    raise e
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/main.py", line 1570, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 864, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Completions.create() got an unexpected keyword argument 'stop_sequences'
```

This is possibly an error with the most recent version of litellm?

**Comment by neubig** [comment]
This should be fixed by updating to OpenHands 0.11.0
