### ISSUE TITLE
Fails to create branch/PR after generating patch: invalid continuation byte

### ISSUE THREAD

**Issue by codegefluester** [All-Hands-AI/openhands-resolver#198]
The step _Create Draft PR or push branch_ fails with the below error. It is a PHP 7.4 repository using Git LFS. Happy to provide any other details you may need. Would be great, in such cases, for resolver to simply attach the patch as an artifact to the action run, then we could at least apply it manually.

```
Run if [ "true" == "true" ]; then
  if [ "true" == "true" ]; then
    cd /tmp && python -m openhands_resolver.send_pull_request \
      --issue-number 80 \
      --pr-type draft | tee pr_result.txt && \
      grep "draft created" pr_result.txt | sed 's/.*\///g' > pr_number.txt
  else
    cd /tmp && python -m openhands_resolver.send_pull_request \
      --issue-number 80 \
      --pr-type branch \
      --send-on-failure | tee branch_result.txt && \
      grep "branch created" branch_result.txt | sed 's/.*\///g; s/.expand=1//g' > branch_name.txt
  fi
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.1[2](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:2).7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:3).12.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.7/x6[4](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:4)
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.7/x64/lib
    ISSUE_NUMBER: 80
    GITHUB_TOKEN: ***
    LLM_MODEL: ***
    LLM_API_KEY: ***
    LLM_BASE_URL: 
    PYTHONPATH: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line [5](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:5)00, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.12.7/x[6](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:6)4/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 489, in main
    process_single_issue(
  File "/opt/hostedtoolcache/Python/3.12.[7](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:7)/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 365, in process_single_issue
    apply_patch(patched_repo_dir, resolver_output.git_patch)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 54, in apply_patch
    split_content = [x.strip(newline) for x in f.readlines()]
                                               ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-[8](https://github.com/**REDACTED**/**REDACTED**/actions/runs/11559530032/job/32174384426#step:10:8)' codec can't decode byte 0xd9 in position 23: invalid continuation byte
Copied repository to output/patches/issue_80
```

**Comment by neubig** [comment]
Hey @codegefluester , thanks! I agree that in the worst case, the branch should still be attached to the run. I'd be interested in taking a look when I have a moment, but it may take a little bit so I'd also welcome a PR!

**Comment by codegefluester** [comment]
I can try my luck, though I am not super proficient with Python so may not be able to do more than a "try-catch" solution - will give it a look regardless but also can't promise anything. Thanks for responding so quickly! It is actually working in our other repositories, the quality is a bit questionable with one of our TypeScript repos where it creates syntax errors, but it tries - happy to give this a go every other week!

**Comment by neubig** [comment]
Hi @codegefluester , I had OpenHands implement the try/catch solution. Things should be somewhat more robust now: #246

**Comment by codegefluester** [comment]
@neubig thanks for looking into this! I do however still see this failure in the GitHub action so maybe it is just something related to our repo? I'll have a quick go with a fork and see if that helps and will let you know how I made it work in the end.

```
Run if [ "true" == "true" ]; then
ERROR:root:  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 587, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 575, in main
    process_single_issue(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 424, in process_single_issue
    apply_patch(patched_repo_dir, resolver_output.git_patch)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/openhands_resolver/send_pull_request.py", line 65, in apply_patch
    split_content = [x.strip(newline) for x in f.readlines()]
                                               ^^^^^^^^^^^^^
  File "<frozen codecs>", line [32](https://github.com/hotlaps/hotlaps-backend/actions/runs/11678876185/job/32519029964#step:10:33)2, in decode

ERROR:root:<class 'UnicodeDecodeError'>: 'utf-8' codec can't decode byte 0xd9 in position 23: invalid continuation byte
Copied repository to output/patches/issue_88
```

I don't think I am doing anything wrong in the workflow file, am I?
```
name: Resolve Issues with OpenHands

on:
  issues:
    types: [labeled]

jobs:
  call-openhands-resolver:
    uses: All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@main
    if: github.event.label.name == 'fix-me'
    with:
      issue_number: ${{ github.event.issue.number }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_MODEL: ${{ secrets.LLM_MODEL }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
```

**Comment by codegefluester** [comment]
@neubig not ideal as a fix I guess but it unblocks us for now https://github.com/hotlaps/openhands-resolver/commit/813cef070a9870283225bb317432ac695ab1d919

**Comment by neubig** [comment]
Hey @codegefluester , thanks a lot for the pointer! I'd like to get this into the main codebase as the following note:
1. the change to `UnicodeDecodeError` to avoid catching general exception
2. the change to `logger.error`

```python
            try:
                with open(old_path, "r", newline=newline) as f:
                    split_content = [x.strip(newline) for x in f.readlines()]
            except UnicodeDecodeError as e:
                logger.error(f"Error reading file {old_path}: {e}")
                split_content = []
```

If you wouldn't mind sending a PR to this effect I'd love to acknowledge your contribution, but if you'd prefer me to send it in I can do it too.

**Comment by codegefluester** [comment]
Cheers! Happy to contribute, will make those changes and send it your way later today.

Sent from my iPhone

On 5 Nov 2024, at 12:17, Graham Neubig ***@***.***> wrote:

﻿

Hey @codegefluester<https://github.com/codegefluester> , thanks a lot for the pointer! I'd like to get this into the main codebase as the following:

            try:
                with open(old_path, "r", newline=newline) as f:
                    split_content = [x.strip(newline) for x in f.readlines()]
            except UnicodeDecodeError as e:
                logger.error(f"Error reading file {old_path}: {e}")
                split_content = []

Note

  1.  the change to UnicodeDecodeError to avoid catching general exception
  2.  the change to logger.error

If you wouldn't mind sending a PR to this effect I'd love to acknowledge your contribution, but if you'd prefer me to send it in I can do it too.
