### ISSUE TITLE
Crash After work done and exiting

### ISSUE THREAD

**Issue by regismesquita** [All-Hands-AI/openhands-resolver#229]
Hi, I believe I am facing a similar issue to #145, I just started using this tool so I am not certain, but seems that my resolver is failing after the work is done and when it is trying to exit the shell.

This error is happening both locally and on the github action.
```
2024-11-01 16:27:12,290 - DEBUG - [Agent Controller default] **CmdRunAction (source=None)**
THOUGHT: I've added a new section to the README.md file that explains:
1. How to use the OpenHands resolver by adding the 'fix-me' label
2. What the workflow does (attempts resolution, creates PR/branch, comments on issue, removes label)
3. Where to monitor the progress

Since this is just a documentation change to the README file, no tests need to be written or run.

Let me finish the task:
COMMAND:
exit
2024-11-01 16:27:12,290 - DEBUG - Adding CmdRunAction id=9 from AGENT
2024-11-01 16:27:12,291 - DEBUG - [runtime 8] Getting container logs...
2024-11-01 16:27:12,392 - ERROR - [runtime 8] Error during action execution: 500 Server Error: Internal Server Error for url: http://localhost:38352/execute_action
2024-11-01 16:27:12,393 - DEBUG - [runtime 8] Getting container logs...
2024-11-01 16:27:12,393 - DEBUG - [runtime 8]
-----------------------------------Container logs:-----------------------------------
    |16:27:12 - openhands:DEBUG: action_execution_server.py:164 - Running action:
    |**CmdRunAction (source=EventSource.AGENT)**
    |THOUGHT: I've added a new section to the README.md file that explains:
    |1. How to use the OpenHands resolver by adding the 'fix-me' label
    |2. What the workflow does (attempts resolution, creates PR/branch, comments on issue, removes label)
    |3. Where to monitor the progress
    |
    |Since this is just a documentation change to the README file, no tests need to be written or run.
    |
    |Let me finish the task:
    |COMMAND:
    |exit
    |16:27:12 - openhands:DEBUG: bash.py:51 - BASH PARSING command: exit
    |16:27:12 - openhands:DEBUG: bash.py:58 - BASH PARSING remaining:
    |16:27:12 - openhands:DEBUG: bash.py:170 - Executing command: exit
    |16:27:12 - openhands:DEBUG: bash.py:253 - Continuing bash with timeout=300
    |16:27:12 - openhands:ERROR: bash.py:131 - Bash shell EOF! self.shell.after=<class 'pexpect.exceptions.EOF'>, self.shell.before='exit\r\n'
    |16:27:12 - openhands:ERROR: action_execution_server.py:405 - Error processing command: Bash shell EOF
    |Traceback (most recent call last):
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 255, in _continue_bash
    |    self.shell.expect(self.__bash_expect_regex, timeout=timeout)
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 354, in expect
    |    return self.expect_list(compiled_pattern_list,
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 383, in expect_list
    |    return exp.expect_loop(timeout)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/expect.py", line 179, in expect_loop
    |    return self.eof(e)
    |           ^^^^^^^^^^^
    |  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/pexpect/expect.py", line 122, in eof
    |    raise exc
    |pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
    |<pexpect.pty_spawn.spawn object at 0xfe46e07e3170>
    |command: /usr/bin/su
    |args: [b'/usr/bin/su', b'openhands']
    |buffer (last 100 chars): ''
    |before (last 100 chars): 'exit\r\n'
    |after: <class 'pexpect.exceptions.EOF'>
    |match: None
    |match_index: None
    |exitstatus: None
    |flag_eof: True
    |pid: 37
    |child_fd: 10
    |closed: False
    |timeout: 30
    |delimiter: <class 'pexpect.exceptions.EOF'>
    |logfile: None
    |logfile_read: None
    |logfile_send: None
    |maxread: 2000
    |ignorecase: False
    |searchwindowsize: None
    |delaybeforesend: 0.05
    |delayafterclose: 0.1
    |delayafterterminate: 0.1
    |searcher: searcher_re:
    |    0: re.compile('\\[PEXPECT_BEGIN\\]\\s*(.*?)\\s*([a-z0-9_-]*)@([a-zA-Z0-9.-]*):(.+)\\s*\\[PEXPECT_END\\]')
    |
    |During handling of the above exception, another exception occurred:
    |
    |Traceback (most recent call last):
    |  File "/openhands/code/openhands/runtime/action_execution_server.py", line 402, in execute_action
    |    observation = await client.run_action(action)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/action_execution_server.py", line 165, in run_action
    |    observation = await getattr(self, action_type)(action)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/action_execution_server.py", line 172, in run
    |    return self.bash_session.run(action)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 298, in run
    |    output, exit_code = self._execute_bash(
    |                        ^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 172, in _execute_bash
    |    return self._continue_bash(
    |           ^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 273, in _continue_bash
    |    bash_prompt = self._get_bash_prompt_and_update_pwd()
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |  File "/openhands/code/openhands/runtime/utils/bash.py", line 132, in _get_bash_prompt_and_update_pwd
    |    raise RuntimeError('Bash shell EOF')
    |RuntimeError: Bash shell EOF
    |Stack (most recent call last):
    |  File "<frozen runpy>", line 198, in _run_module_as_main
    
    
    ...
    
    
        |16:27:15 - openhands:ERROR: action_execution_server.py:361 - HTTP exception occurred: Bash shell EOF
--------------------------------------------------------------------------------
2024-11-01 16:27:15,163 - INFO - **FatalErrorObservation**
Action execution failed: 500 Server Error: Internal Server Error for url: http://localhost:38352/execute_action
2024-11-01 16:27:15,163 - INFO - Finished.
2024-11-01 16:27:15,163 - DEBUG - Adding AgentStateChangedObservation id=12 from AGENT
2024-11-01 16:27:15,163 - DEBUG - Adding AgentStateChangedObservation id=13 from AGENT
```

_Originally posted by @regismesquita in https://github.com/All-Hands-AI/openhands-resolver/issues/145#issuecomment-2452205232_

**Comment by malhotra5** [comment]
I think this may be due to the new function calling updates on `Openhands`?

I believe this line may be causing issues in `openhands-resolver/prompts/resolve/basic-with-test.jinja`

> When finished, run the following command: <execute_bash> exit </execute_bash>.

Versus the prompt for `openhands-resolver/prompts/resolve/basic.jinja` has 

> When you think you have fixed the issue through code changes, please finish the interaction.

We could confirm this by running openhands-resolver with `--prompt-file openhands-resolver/prompts/resolve/basic.jinja`?

**Comment by regismesquita** [comment]
Thank you @malhotra5 it is working as expected now!
